set nocompatible

execute pathogen#infect()

"Option to remove any traces in .viminfo
set viminfo=/5,'0,:5,<0,@0,f0
"            |  |  |  |  |  '-file marks 0-9,A-Z not saved               
"            |  |  |  |  '-input-line history not saved
"            |  |  |  '-registers not saved
"            |  |  '-5 last command-line history saved
"            |  '-file marks not saved
"            '-5 recent search history will be saved
"        no % : buffer list not saved

"General options for all files
"ruler options
set ruler
set number
set relativenumber
set linebreak "backspace support
set wildmenu
set wildignore=*.pdf,*.png,*.eps,*.o
"case-insensitive file completion
set wildignorecase
set mouse=a
" split configs
set splitright
"nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>w
nnoremap <C-l> <C-W>l
cnoreabbrev Q q

set magic
vmap C "+y
set whichwrap+=<,>,[,]

set t_Co=256 "256 colors
"gvim configs
if has('gui_running')
    colorscheme badwolf "gurunew
    set guioptions-=T  "remove toolbar
    set guioptions-=r  "remove right-hand scroll bar
    set guioptions-=L  "remove left-hand scroll bar
else
    colorscheme munger2 "eldar elflord
    "set to goldenrod for gray comments
endif

if &diff
    colorscheme goldenrod
endif

"Code options
set modeline
set tabstop=4
set shiftwidth=4
"set smarttab
set expandtab
set clipboard=unnamedplus
set cindent  "indent like C code

"Options for search features
set hlsearch
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
set incsearch
set ignorecase
set smartcase

"Indentation for makefiles
"set noet ci pi sts=0 sw=4 ts=4

"Remap NERDTree command
:command NT NERDTree

filetype plugin on
filetype indent on
syntax on
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

let g:tex_flavor='latex'


"CSV parameters
" NewDelimiter ; "changes the delimiter
" let g:csv_delim=';'

"statusline options
set laststatus=2
set statusline=   " clear the statusline for when vimrc is reloaded
set statusline+=%-3.3n\                      " buffer number
set statusline+=%f\                          " file name
set statusline+=%h%m%r%w                     " flags
set statusline+=[%{strlen(&ft)?&ft:'none'},  " filetype
set statusline+=\ %{strlen(&fenc)?&fenc:&enc}, " encoding
set statusline+=\ %{&fileformat}]              " file format
set statusline+=%=                           " right align
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}\  " highlight
set statusline+=%b,0x%-8B\                   " current char
set statusline+=%-14.(%l,%c%V%)\ %<%P        " offset
""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"airline status-line
"airline disabling switch
let g:loaded_airline = 1
if g:loaded_airline
    let g:airline_section_b = '%f'
    let g:airline_section_c = '%{strlen(&fenc)?&fenc:&enc}, %{&fileformat}'
    let g:airline_section_d = "%{synIDattr(synID(line('.'),col('.'),1),'name')}"
    let g:airline#extensions#default#layout = [
          \ [ 'a', 'b', 'c' ],
          \ [ 'x', 'z', 'error', 'warning' ]
          \ ]
    let g:airline#extensions#tabline#enabled = 0
    " let g:airline#extensions#tabline#left_sep = ' '
    " let g:airline#extensions#tabline#left_alt_sep = '|'
    let g:airline_theme='dark' " :AirlineTheme
endif

"set shell=/bin/bash\ -i
inoremap <C-s> <C-o>:update<CR>
nnoremap <C-s> :update<CR>
set iskeyword-=58 "colon

"EasyAlign plugin
"nnoremap ga :EasyAlign<CR>

"cd to current buffer
"autocmd BufEnter * silent! lcd %:p:h

"disable auto-commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" vim -b : edit binary using xxd-format!
augroup Binary
    au!
    au BufReadPre  *.bin let &bin=1
    au BufReadPost *.bin if &bin | %!xxd
    au BufReadPost *.bin set ft=xxd | endif
    au BufWritePre *.bin if &bin | %!xxd -r
    au BufWritePre *.bin endif
    au BufWritePost *.bin if &bin | %!xxd
    au BufWritePost *.bin set nomod | endif
augroup END


"Tags options
"Exuberant-ctags location
let Tlist_Ctags_Cmd='/usr/bin/ctags'
let g:Tlist_Use_Split_Window=0

" Leader options
let mapleader = "é"
"nnoremap <leader>d dd

"maplocalleader -> leader for specific filetype
